# Generated by Django 4.2.1 on 2023-05-21 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Sundmus", models.CharField(max_length=200)),
                (
                    "Olulisus",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                ("Kuupaev", models.DateField(verbose_name="")),
                ("Lisa", models.CharField(max_length=150)),
                ("Alguskuupaev", models.DateField()),
                ("Loppkuupaev", models.DateField()),
            ],
        ),
    ]
