# Generated by Django 4.2.1 on 2023-06-02 06:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0002_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 9, 1, 41, 111231)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 9, 1, 41, 111231)),
        ),
    ]
