# Generated by Django 4.2.2 on 2023-06-13 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalender', '0005_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 8, 46, 53, 572972)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 8, 46, 53, 572919)),
        ),
    ]
